demo of project
moevm/lab_report_grabber pull request #8
Opened 2023-12-20 11:53 UTC by MikelazDotPy

Еще не пофикшены запрошенные изменения, рабочий прототип к созвону 20.12

2023-12-20 15:20 UTC, zmm commented on main.py
> +
Добавьте if __name__

2024-01-10 12:41 UTC, zmm commented on parse_table.py
> +        raise Exception("Work with file error")
Нужно уточнить что за ошибка и написать о ней чуть подробнее - может и путь к файлу быть кривой, и права доступа, и формат некорректный

2024-01-10 12:46 UTC, zmm commented on parse_github.py
> +def parse_repo(args, table):
В данном методе также нужна обработка исключений, поскольку пользователи очень любят ошибатся в токене, запрашивать доступ к репо, где у них нет прав и тд. 
Оберните необходимые методы и выдавайте подробные сообщения.

2024-01-10 12:47 UTC, zmm commented on fill_table.py
> +        writer.writerows(rows)
Обработайте исключения, связанные с записью в файл.

2024-01-10 12:48 UTC, zmm commented on parse_github.py
> +        if content.name == 'src' and content.type == 'dir':
Есть небольшой шанс, что в будущем вашу утилиту будут использовать для репо с другой структурой. чтобы утилита была более гибкой, нужно привязки к нашей специфике сделать +- гибкими. Для начала предлагаю константу 'src' сделать именованной -так в будущем в таком гипотетическом сценарии будет проще адаптироваться.

2024-01-10 12:51 UTC, zmm commented on get_args.py
> +
Параметрам выше необходимы (если они уместны) 
- значения по умолчанию
- флаг required

2024-01-19 17:16 UTC, mirrin00 requested changes
Небольшие замечания по организации репозитория:
* Все или большинство файлов с исходным кодом кладут в специальную папку, обычно в папку `src`
* Нужно сделать README о том, как поставить зависимости и как запустить

Оно работает, но не полностью (баг или я  не понимаю, ка киспользовать): не находит часть студентческих работ. Как воспроизвести:
1. Скачать таблицу рейтинга за весенний семестр
2. (Добавил в код приведение никнейма к нижнему регистру)
3. Запустить для группы 3388: `python3 main.py -p ../lab_generator_grade_table.csv  --full_name_col 1 --group_col 2 --github_col 6 --prefix moevm/pr-2023-3388 --token_file ../token_file -s ../pr_labs.csv -o result2.csv`
4. Не хвататет работ следующих студентов: Лутфулин, Поляков, Пьянков, Сабалиров, Снигерев, Сурова, Тимощук, Трунов, ...

Оставил ещё несколько комментариев к коду

2024-01-24 00:15 UTC, MikelazDotPy commented on parse_table.py
> +        exit(0)
Там везде внутри with разные команды, пока не придумал, как это обрабатывать

2024-01-24 01:10 UTC, MikelazDotPy commented on parse_github.py
> +            index = content.name.rfind('_')
Нужны ли английские имена студентов? Русские из таблички тянутся

2024-01-24 02:17 UTC, MikelazDotPy commented
Можно ли пренебречь тем фактом, что в мейне может оказаться ЛР не соответствующая формату? Просто у меня один человек не читался, потому что папка называлась не "src", а "scr"

2024-01-24 08:24 UTC, mirrin00 commented on parse_github.py
> +            index = content.name.rfind('_')
Можно сделать отдельной группой в регулярных выражениях. Пока они не нужны, но смогут пригодиться потом + меньше зависимостей от логина на github'а будет (как раз недавно студентка поменяла github, теперь сопоставление по логину для неё не сработает)

2024-01-24 08:25 UTC, mirrin00 commented on parse_table.py
> +        exit(0)
Логика примерная как с `qsort` -- можно в качестве аргумента передавать функцию, которая что-то сделает и вернет результат

2024-01-24 08:27 UTC, mirrin00 commented
> Можно ли пренебречь тем фактом, что в мейне может оказаться ЛР не соответствующая формату? Просто у меня один человек не читался, потому что папка называлась не "src", а "scr"

Можно, но нужно вывести какую-то ошибку или что-то очень похожее (или создавать второй csv файл, в котором будут список студентов и ошибка, из-за которой не удалось их обработать). Суть этого в том, чтобы потом понять: у студента нет кода потому что он не сделал или потому что есть какая-то ошибка (и чья ошибка -- мержа или скрипта сбора)

2024-01-24 12:30 UTC, MikelazDotPy commented
Сделал варнинги. В логах по поиску можно будет быстро найти такого человека

2024-03-20 11:30 UTC, zmm commented on input/token.txt
> +ghp_MyGitHubToken
Пример файла не нужен - отразите в документации (и для других в input)

2024-03-20 11:30 UTC, zmm commented on src/fill_table.py
> +        exit(0)
Здесь и в других подобных местах - в случае ошибок делаем exit(1)

2024-03-20 11:32 UTC, zmm commented on README.md
> +3. Создание виртуального окружения
Давайте для полной красоты (и дальнейшей обертки в докер) укажем конкретную версию пайтона, на которой вы тестировали.

2024-07-05 07:17 UTC, thehighestmath requested changes

2024-07-05 07:17 UTC, thehighestmath commented on main.py
> +        exit(0)
`exit(0)` -- успешное завершение программы
а вот исключение -- это неуспешное завершение, давайте использовать код отличный от нуля)

2024-07-05 07:17 UTC, thehighestmath commented on requirements.txt
> +wrapt==1.16.0
кажется, что не все либы нужны, часть из них транзитивно скачиваются, это ок, но по существу нужно меньше либ выкачать
https://pip.pypa.io/en/stable/topics/dependency-resolution/

2024-07-05 07:17 UTC, thehighestmath commented on src/classes.py
может лучше вместо обычных классов заиспользовать датаклассы? что думаете?
https://docs.python.org/3/library/dataclasses.html

тут просто только данные храняться, + 1-2 метода который просто немного дает представление о классе

после изменений лучше код протестировать)

2024-07-05 07:17 UTC, thehighestmath commented on src/classes.py
> +            code += cfg['Const']['code_format'].format(file_name=file_name, code=self.code[file_name])
конкатенация строк в цикле -- временная сложность `O(n^2)`
лучше использовать список, добавлять в него, а потом сделать `join`

вот тут подробнее описал почему так плохо https://github.com/thehighestmath/umschool-final-task/blob/master/review_comments.md#2-%D0%BA%D0%BE%D0%BD%D0%BA%D0%B0%D1%82%D0%B5%D0%BD%D0%B0%D1%86%D0%B8%D1%8F-%D1%81%D1%82%D1%80%D0%BE%D0%BA-%D0%B2-%D1%86%D0%B8%D0%BA%D0%BB%D0%B5---%D1%8D%D1%82%D0%BE-%D0%B7%D0%BB%D0%BE

2024-07-05 07:17 UTC, thehighestmath commented on src/parse_github.py
> +    except:
давайте сохраним ошибку куда-нибудь?

2024-07-05 07:17 UTC, thehighestmath commented on src/parse_github.py
> +    g = try_auth(cfg['Error']['github_auth'], args['token_file'])
g -- github?
лучше не использовать однобуквенные переменные :(

2024-07-05 08:09 UTC, thehighestmath reviewed
Код запустил, но лучше придумать публичную репу, на которой можно код потестить, будет здорово)

Правильно ли я понимаю, что сейчас утилита умеет бегать по репозиториям, находить все лабы, валидировать  структуру файлов
вытаскивать исходный код. верно?

2024-07-05 08:10 UTC, thehighestmath commented on README.md
> +|`--token_file`ИЛИ `--token`| Файл с github токеном в первой строке / github токен
UPD: нашёл как получить токен, но хотелось бы минимальный набор доступов который нужно использовать, чтобы лишнего не натыкать

2024-07-08 14:14 UTC, closed without merging